### ISSUE TITLE
As a participant in a round, I want to be able to chat with other participants once the round is over in order to discuss other people’s submissions

### ISSUE THREAD

**Issue by Figo2003** [sopra-fs24-group-12/PeekSeek-server#13]
**Acceptance Criteria**

- [ ] Next to each message, the username of the participant sending a message is shown.
- [ ] A notification sound is played once a new message arrives.
- [ ] The chat is aligned at the right of the page once the submission presentation starts but hidden while each participant is playing their round

**Development Tasks**

- [ ] sopra-fs24-group-12/PeekSeek-client#7
- [ ] sopra-fs24-group-12/PeekSeek-client#5
- [ ] sopra-fs24-group-12/PeekSeek-client#4
