### ISSUE TITLE
As a participant in a round, I want to be shown the voting results after each round in order to feel competitive

### ISSUE THREAD

**Issue by Figo2003** [sopra-fs24-group-12/PeekSeek-server#15]
**Acceptance Criteria**

- [ ] #93
- [x] The total points should be shown in a leaderboard, revealing the current standings after each round.

**Development Tasks**

- [ ] sopra-fs24-group-12/PeekSeek-client#3
- [ ] sopra-fs24-group-12/PeekSeek-client#6
- [ ] sopra-fs24-group-12/PeekSeek-server#67
