### ISSUE TITLE
As a user, I want to be able to create a lobby in order for a group to join

### ISSUE THREAD

**Issue by Figo2003** [sopra-fs24-group-12/PeekSeek-server#3]
**Acceptance Criteria**

- [x] A user sees all the lobbies on the "join lobby" page.
- [x] A user can create a lobby by pressing a “create new game” button.
- [x] The creator of the lobby is set to the admin of the lobby.
- [x] The admin is redirected to a new page where he can set the lobby name and a lobby password.
- [x] #121
- [ ] The creation date and time of the lobby creation are recorded in the database.

**Development Tasks**

- [x] sopra-fs24-group-12/PeekSeek-server#45
- [x] sopra-fs24-group-12/PeekSeek-client#15
- [x] sopra-fs24-group-12/PeekSeek-client#17
- [x] sopra-fs24-group-12/PeekSeek-server#48
- [x] sopra-fs24-group-12/PeekSeek-client#14
- [x] sopra-fs24-group-12/PeekSeek-server#49
