### ISSUE TITLE
As an admin of a lobby, I can create a list of quests, which correspond to one game round, in order to specify individual game rounds

### ISSUE THREAD

**Issue by Figo2003** [sopra-fs24-group-12/PeekSeek-server#5]
**Acceptance Criteria**
- [x] A quest describes a spot to be located within a round
- [ ] The admin can choose from a list of predefined quests
- [x] The admin can create their own quest types by typing it in a form field
- [x] The quests are visible on the lobby dashboard

**Development Tasks**
- [x] sopra-fs24-group-12/PeekSeek-client#11
- [x] sopra-fs24-group-12/PeekSeek-client#12
- [x] sopra-fs24-group-12/PeekSeek-client#53
- [x] sopra-fs24-group-12/PeekSeek-server#56
