### ISSUE TITLE
create the needed file structure of the project

### ISSUE THREAD

**Issue by emmge** [sopra-fs24-group-12/PeekSeek-server#78]
**Development Tasks**

- [ ] sopra-fs24-group-12/PeekSeek-server#72
- [ ] sopra-fs24-group-12/PeekSeek-server#73
- [ ] sopra-fs24-group-12/PeekSeek-server#74
- [ ] sopra-fs24-group-12/PeekSeek-server#75
- [ ] sopra-fs24-group-12/PeekSeek-server#76
- [ ] sopra-fs24-group-12/PeekSeek-server#77
