### ISSUE TITLE
As a participant in a round,I want to be shown interesting trivia about the chosen city in the waiting room at the end of the round, in order to keep the user engaged in the game

### ISSUE THREAD

**Issue by Figo2003** [sopra-fs24-group-12/PeekSeek-server#9]
**Acceptance Criteria**

- [ ] Trivia should include facts, historical information, cultural insights, or notable places to visit in the city.
- [ ] New trivia appears at regular intervals to keep the participant engaged while waiting.
- [ ] Once all participants have completed the round, the trivia display should smoothly transition to game summary.

**Development Tasks**

- [x] sopra-fs24-group-12/PeekSeek-client#8
- [ ] sopra-fs24-group-12/PeekSeek-server#60
- [ ] sopra-fs24-group-12/PeekSeek-server#61
